return PlaceObj('ModDef', {
	'title', "Rato's AI Overhaul",
	'description', "Features\n\nLogic for keeping stance AP\n\nAI will be able to use single shot instead of burst shot if  otherwise it wouldnt have enough AP to enter shooting stance\n\nAi will crouch or go prone if it has ap at the end of its turn\n\nEnemies wont hang back, they will enter the fight\n\nMore aiming, more shooting stance entering.\n\nCustom decision making when AI decides to use special attacks like mobile attack, overwatch, limb shots, etc. The logic is based on distance, weapons and components, and takes into effect the new mechanics from GBO.\n\nThe AI will be able to use most of the abilities of new weapons/components added by CUAE (example, a stockless rifle will use run and gun, SKS users will use their mobile attacks, they will be able to use grenades).\n\nCustom logic for Grenadiers and MGs to try to attack targets in cover and destroy the cover\n\nMore use of grenades. (specialists will use more)\n\nEnemies will try to not be flanked or out of cover. \n\nUnits will throw flares at the enemy at night.\n\nCreated a custom experimental logic for AI to flank more efficiently \n\nRevamped source functions that control the inner workings of the AI decision making. Added recoil calculation, point blank mechanics changes from GBO, cover, mechanics changes. The AI will take into account Bolt Action costs when making decisions.\n\nFixed some behaviors that made AI use FreeMove ap for aiming.\n\nAlso took away some limitations AI had to make it less punishing in the base game.\n\nIncreased AI use of cover. \nIncreased AI use of MGsetup.\n\nSnipers will swap to handguns and start retreating behaviors when you get too close to them.\n\nNew lore friendly weapon progression to be used with CUAE!\n\nThe philosophy here was to change mostly/only the behavior of the AI, with no cheating (I even fixed some cheating the AI did). \n\n\nThe only additions to units are increased explosive stats skill (if you use Rato's Explosive Overhaul, this is recommended) and the addition of Heavy Weapon's Specialist to machine gunners. Both can be disabled in the mod options\n\n\n\nFair Play Philosophy\n\n    The AI improvements focus solely on enhancing behavior, avoiding any unfair advantages or \"cheating.\" \n\nImproved Tactics for Grenadiers and Machine Gunners\n\n    Grenadiers and MG units are more adept at targeting enemies in cover, prioritizing cover destruction.\n    Increased grenade usage for both offensive and tactical purposes.\n\nNight Combat Enhancements\n\n    Units now throw flares at enemies during night time engagements for improved visibility and tactical advantage.\n\nExperimental Flanking Logic\n\n    Custom experimental logic improves AI flanking behaviors for more effective positioning and tactical maneuvers.\n\nCore AI Mechanics Overhaul\n\n    Revamped source functions governing AI decision-making. Updates include:\n        Recoil calculation and point-blank mechanics from GBO.\n        Enhanced cover mechanics and Bolt Action AP cost considerations.\n        Fixed behaviors causing AI to misuse FreeMove AP for aiming in vanilla.\n\nBehavioral Adjustments for Realism and Balance\n\n    Removed certain base game limitations to make AI more challenging.\n    Increased AI usage of cover and MG setups for strategic advantage.\n    Snipers now swap to handguns and adopt retreat behaviors when enemies close in.\n\nLore-Friendly Weapon Progression (CUAE)\n\n    Added a lore-friendly progression system for new weapons compatible with CUAE.\n\nOptional:\n        Explosive skill stats increased for all units (recommended with Rato’s Explosive Overhaul, but optional).\n        Machine Gunners gain the Heavy Weapons Specialist perk (can be disabled via mod options).",
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "cfahRED",
			'title', "Rato's Gameplay Balance and Overhaul 3",
			'version_major', 3,
			'version_minor', 51,
		}),
	},
	'id', "RATOAI",
	'author', "rato",
	'version', 2441,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'code', {
		"Code/Const_APstance.lua",
		"Code/PATCH_AppendClass_source_classes.lua",
		"Code/PATCH_UnitData.lua",
		"Code/PATCH_call.lua",
		"Code/PATCH_ChangeUnitDataDef.lua",
		"Code/DEBUG.lua",
		"Code/AIPOLICYPOS_CustomFlanking.lua",
		"Code/AIPOLICYPOS_CustomSeekCover.lua",
		"Code/AIPOLICYPOS_TryNotToBeFlanked.lua",
		"Code/AIPOLICYPOS_MGSetupPosScore.lua",
		"Code/AIPOLICYPOS_Attack_StanceAP.lua",
		"Code/AIPOLICYPOS_MGSetupAP.lua",
		"Code/AIPOLICYTARG_EnemyInCover.lua",
		"Code/AIPOLICYPOS_SaveAP.lua",
		"Code/AIPOLICYPOS_GrenadeRange.lua",
		"Code/AIACTION_ThrowFlare.lua",
		"Code/AIACTION_PrepareWeapon.lua",
		"Code/UTIL.lua",
		"Code/CUAE_options.lua",
		"Code/FUNCTION_ChangeEquipment.lua",
		"Code/FUNCTION_EndTurnAIAction.lua",
		"Code/FUNCTION_ShouldMaxAim.lua",
		"Code/FUNCTION_getAIShootingStanceBehaviorSelectionScore.lua",
		"Code/FUNCTION_getAISoldierFlankingBehaviorSelectionScore.lua",
		"Code/FUNCTION_Get_HeavyGunnerShouldUsePositioningBehavior.lua",
		"Code/FUNCTION_get_ShouldUseGetCloserPositioningBehavior.lua",
		"Code/FUNCTION_SignaturesCustomScoring.lua",
		"Code/FUNCTION_CustomArchetypeFunc.lua",
		"Code/PROPERTIES_Unit.lua",
		"Code/SOURCE_FreeMove.lua",
		"Code/SOURCE_AIPrecalcDamageScore.lua",
		"Code/SOURCE_AIPlayAttacks.lua",
		"Code/SOURCE_AICalcAttacksandAim.lua",
		"Code/SOURCE_SelectArchetype.lua",
		"Code/SOURCE_AICreateContext.lua",
		"Code/SOURCE_AIGetAttackArgs.lua",
		"Code/SOURCE_AIGetBias.lua",
		"Code/SOURCE_AISelectAction.lua",
		"Code/SOURCE_AIEvalZones.lua",
		"Code/SOURCE_AITakeCover.lua",
		"Code/SOURCE_AIPolicyIndoorsOutdoors_EvalDest.lua",
		"Code/SOURCE_AIActionThrowGrenadePrecalcAction.lua",
		"Code/vanilla_archetype_functions_forconsult.lua",
		"Code/vanilla_action_functions_forconsult1.lua",
		"Code/AIPrecalcConeTargetZones.lua",
		"Code/AIScoreReachableVoxels.lua",
		"Code/eval_dest.lua",
		"Code/Script.lua",
		"Code/AIExecuteUnitBehavior.lua",
		"Code/Test.lua",
		"UnitData/AdonisSniper_Elite_copy.lua",
		"UnitData/LegionGrenadier_copy.lua",
		"UnitData/LegionGunner_copy.lua",
		"UnitData/LegionRaider_copy_copy.lua",
		"UnitData/LegionRaider_copy.lua",
		"UnitData/LegionScout_copy.lua",
		"UnitData/LegionButcher_copy.lua",
	},
	'default_options', {
		AddFlares = true,
		AddHWStoGunners = true,
		CUAELoreProgression = true,
		ImproveExplosiveStat = true,
		VanillaFreeMoveBonus = 0,
	},
	'has_data', true,
	'saved', 1736842509,
	'code_hash', 8873859702124773377,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "ShootingStance_Archetype",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "ShootingStance_Archetype_copy",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "FLARES",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "he",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "AdonisSniper_Elite_copy",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionGrenadier_copy",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionGunner_copy",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRaider_copy_copy",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionRaider_copy",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionScout_copy",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "LegionButcher_copy",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Soldier",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "RATOAI_Sniper",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Skirmisher",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "RATOAI_RetreatingMarksman",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "RATOAI_Demolition",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "HeavyGunner",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Brute",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Medic",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "RATOAI_UnboltedWeapon",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Medic_copy",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Artillery",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "PierreGuard",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Pierre",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "TheMajor",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Scout_LastLocation_copy",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "PinnedDown_copy",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Turret_copy",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Beast_Crocodile_copy",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Beast_Hyena_copy",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Bossfight_GuardArea_copy",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Corazon_BossRetreating_copy",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Corazon_GuardArea_copy",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Corazon_KiteBack_copy",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Corazon_ShootAndScoot_copy",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "Faucheaux_BossRetreating_copy",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "CorazonBoss_copy",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "TurretBoss_copy",
			'ClassDisplayName', "AI Archetype",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AIArchetype",
			'Id', "EmplacementGunner_copy",
			'ClassDisplayName', "AI Archetype",
		}),
	},
	'TagCombat&AI', true,
})